importScripts(
  "../compat/browser_api.js",
  "../compat/platform.js",
  "../shared/build_info.js",
  "../shared/placeholders.js",
  "../shared/ipClassification.js",
  "../shared/ipDetection.js",
  "../shared/networkHierarchy.js",
  "../shared/placeholderAllocator.js",
  "../shared/sessionMapStore.js",
  "../shared/transformOutboundPrompt.js",
  "../shared/redactor.js",
  "../shared/protected_sites.js",
  "../shared/policy.js",
  "./core.js"
);
