(function () {
  const root = typeof globalThis !== "undefined" ? globalThis : window; root.PWM = root.PWM || {};
  const { enterpriseTokenScore, hasProviderContext, hasEnterpriseContext } = root.PWM.CloudScoring;
  function push(findings, detector, raw, start, end, placeholderType, score, methods) { if (!raw || detector.isAllowlisted(raw)) return; findings.push(detector.buildFinding({ category: "internal_metadata", placeholderType, raw, start, end, score, methods })); }
  function cloudScore(input, raw, start, end, base = 48) { let score = base + enterpriseTokenScore(raw); if (hasProviderContext(input, start, end)) score += 14; if (hasEnterpriseContext(input, start, end)) score += 8; return score; }
  function scan(text, detector) { const findings = []; const input = String(text || "");
    for (let match, re = /\b(?:(?:otc-)?(?:ecs|evs|vpc|subnet|sg|security-group|obs|cce|rds|elb|eip|keypair|image|flavor|as|nat|vpn)|otc)-[a-z0-9][a-z0-9-]{4,62}\b/gi; (match = re.exec(input)) !== null;) { const raw = match[0]; const type = /^obs-/i.test(raw) ? "OBS_BUCKET" : hasProviderContext(input, match.index, match.index + raw.length) ? "OTC_RESOURCE" : "OPENSTACK_RESOURCE"; const score = cloudScore(input, raw, match.index, match.index + raw.length, 46); if (score >= 70) push(findings, detector, raw, match.index, match.index + raw.length, type, score, ["cloud-provider", "otc-openstack", "resource"]); }
    for (let match, re = /\b(project_id|projectId|tenant_id|tenantId|domain_id|domainId|user_id|userId|server_id|serverId|instance_id|instanceId|volume_id|volumeId|image_id|imageId|flavor_id|flavorId|vpc_id|vpcId|subnet_id|subnetId|security_group_id|securityGroupId|router_id|routerId|network_id|networkId|port_id|portId)\b\s*[:=]\s*["']?([0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/gi; (match = re.exec(input)) !== null;) { const key = match[1].toLowerCase(); const raw = match[2]; const start = match.index + match[0].lastIndexOf(raw); let type = "OPENSTACK_RESOURCE_ID"; if (key.includes("project")) type = "OPENSTACK_PROJECT_ID"; else if (key.includes("tenant")) type = "OPENSTACK_TENANT_ID"; else if (key.includes("domain")) type = "OPENSTACK_DOMAIN_ID"; else if (key.includes("user")) type = "OPENSTACK_USER_ID"; push(findings, detector, raw, start, start + raw.length, type, 88, ["cloud-provider", "openstack", "id", "context-key"]); }
    for (let match, re = /\b[a-z0-9][a-z0-9.-]{1,100}\.(?:obs\.(?:eu-de|eu-nl)\.otc\.t-systems\.com|otc\.t-systems\.com)\b/gi; (match = re.exec(input)) !== null;) push(findings, detector, match[0], match.index, match.index + match[0].length, match[0].includes(".obs.") ? "OTC_ENDPOINT" : "CLOUD_ENDPOINT", 88, ["cloud-provider", "otc", "endpoint"]);
    return findings; }
  root.PWM.CloudProviderDetectors = root.PWM.CloudProviderDetectors || {}; root.PWM.CloudProviderDetectors.otcOpenStack = { scan };
})();
